apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  accessModes: {{ .Values.pv.accessModes | toYaml | nindent 4 }}
  capacity: {{ .Values.pv.capacity | toYaml | nindent 4 }}
  nfs: {{ .Values.pv.nfs | toYaml | nindent 4 }}