apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
  - name: nfs
    port: {{ .Values.ports.nfs }}
  - name: mountd
    port: {{ .Values.ports.mountd }}
  - name: rpcbind
    port: {{ .Values.ports.rpcbind }}
  selector:
    role: nfs-server
